name-template: 'v$RESOLVED_VERSION 🎁'
tag-template: 'v$RESOLVED_VERSION'

template: |
  $CHANGES

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking Changes
    label: breaking
  - title: 🚀 New Features
    label: feature
  - title: ✨ Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📝 Documentation
    label: documentation
  - title: 📦 Dependency Updates
    label: dependencies
  - title: 🔧 Internal Changes
    label: internal
  - title: 🚦 Tests
    label: tests

version-resolver:
  major:
    labels:
      - 'removed'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'deprecated'
      - 'dependencies'
      - 'documentation'
      - 'tests'
      - 'internal'
  patch:
    labels:
      - 'bug'
  default: minor

replacers:
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: '[JENKINS-$1](https://issues.jenkins.io/browse/JENKINS-$1) - '
